### ISSUE TITLE
Missing argument to devm_kzalloc in phy_zynq_usb.c

### ISSUE THREAD

**Issue by ashish-k29** [Xilinx/linux-xlnx#17]
At line 1973 
xotg->otg.otg = devm_kzalloc(sizeof(struct usb_otg), GFP_KERNEL);
devm_kzalloc is missing the 0th argument, which should be the type of structure to allocate memory for. This missing parameter causes the kernel compilation to fail.

**Comment by michalsimek** [comment]
Driver was redesign and this part was removed.
