### ISSUE TITLE
AXI DMA Driver Does Not Wait For Hardware to Start or Halt

### ISSUE THREAD

**Issue by josephzavodny** [Xilinx/linux-xlnx#39]
The functions dma_start() and dma_halt() check the wrong conditions.  It is possible for these functions to return before the hardware has actually started or halted.  Here is the offending code:

<pre>
/* Start the hardware. Transfers are not started yet */
static void dma_start(struct xilinx_dma_chan *chan)
{
	int loop = XILINX_DMA_HALT_LOOP;

	dma_write(chan, XILINX_DMA_CONTROL_OFFSET,
		  dma_read(chan, XILINX_DMA_CONTROL_OFFSET) |
		  XILINX_DMA_CR_RUNSTOP_MASK);

	/* Wait for the hardware to start */
	while (loop) {
/* WRONG CONDITION */
		if (dma_read(chan, XILINX_DMA_CONTROL_OFFSET) &
		    XILINX_DMA_CR_RUNSTOP_MASK)
			break;

		loop -= 1;
	}
}
</pre>

According to the AXI DMA v7.1 documentation, "The halted bit in the DMA
Status register deasserts to 0 when the DMA engine begins operations".  The code above waits for the RunStop bit in the Control register to go high, but it is supposed to wait for the Halted bit in the Status register to go low.  Replace the condition above with

<pre>if(!(dma_read(chan, XILINX_DMA_STATUS_OFFSET) &
		    XILINX_DMA_SR_HALTED_MASK))</pre>

The function dma_halt() has the same issue.  As stated in the documentation, "There can be a lag of time between when DMACR.RS = 0 and when DMASR.Halted = 1".  dma_halt() must wait for the Halted bit in the status register to go high.

**Comment by nicolaerosia** [comment]
please check if this is fixed

**Comment by josephzavodny** [comment]
Your patch looks good to me.  Changing status to closed.  Thanks.
