### ISSUE TITLE
Cadence WDT Driver Ignores Device Tree Timeout

### ISSUE THREAD

**Issue by josephzavodny** [Xilinx/linux-xlnx#48]
The Cadence driver ignores any timeout specified in the device tree unless the driver is built as a module and loaded into the kernel with an invalid value for the timeout parameter.  The value read from the device tree is always overwritten by the default value of 10 seconds.

The offending code starts at line 367 of cadence_wdt.c.  wdt_timeout is a static variable that is initialized to 10.  The value from the device tree is loaded to the variable cdns_wdt_device->timeout which then immediately gets replaced by wdt_timeout.

<pre>of_property_read_u32(pdev->dev.of_node, "timeout-sec",
			     &cdns_wdt_device->timeout);
	if (wdt_timeout < CDNS_WDT_MAX_TIMEOUT &&
	    wdt_timeout > CDNS_WDT_MIN_TIMEOUT)
		cdns_wdt_device->timeout = wdt_timeout;</pre>

**Comment by michalsimek** [comment]
yes, you are right. There is watchdog driver in the mainline which doesn't have this problem. For 2015.1 I have a patch which is syncing this driver with mainline one. 
Thanks for reporting this,
Michal
