### ISSUE TITLE
USB Gadget multi driver not working since 3.19

### ISSUE THREAD

**Issue by njpillitteri** [Xilinx/linux-xlnx#57]
Since I upgraded to the 3.19 kernel, I can no longer get the USB gadget multi driver to work. I'm using the Zynq USB in peripheral mode. Once I plug in my PC, the Zynq Linux console locks up with no error messages or anything.

**Comment by njpillitteri** [comment]
At some point, I'm going to try using the old Zynq USB driver from the 3.18 kernel instead of the Chipidea one and see if that fixes it.

**Comment by njpillitteri** [comment]
I've still only used the Chipidea driver, but I'm not having issues with the Ethernet+Serial driver, just the multi driver.

**Comment by josephzavodny** [comment]
I ran into this issue a while back but haven't had a chance to look for the bug.  Try limiting the max transfer unit (mtu) on your PC to 512.  I suspect a bug in the ChipIdea driver related to splitting large chunks of data(i.e. ethernet frames) into chunks suitable for USB.  Anyway, the following command should work if you are running Linux on your PC- just replace usb0 with the name of your virtual network interface.

ifconfig usb0 mtu 512

**Comment by michalsimek** [comment]
Can you please retest on the latest code in master branch? We have done some changes recently and this problem should be also solved.

**Comment by njpillitteri** [comment]
Joseph,
Thanks. That solves the gadget ethernet problem, but mass storage still doesn't work.

Michael,
I will give that a try, but there hasn't been many commits to the 3.19 merge, and I don't see any related to USB (including the 4.0 merge) except for a change to a ZC706 devicetree.

**Comment by josephzavodny** [comment]
Michael, are you talking about commit https://github.com/Xilinx/linux-xlnx/commit/2516e422d06d69e3432b081661dfab4b0a16656b#diff-8d6888d7874f9c9e6d90e10acf34217a

If I interpret this correct, applying this patch and updating the .compatible to "xlnx,zynq-usb-2.20a" in your device tree should fix the problem.

**Comment by michalsimek** [comment]
yes, that's the patch I am referring to. And changes you described are correct.

**Comment by njpillitteri** [comment]
Thanks that fixed it
