### ISSUE TITLE
maxcpus=1 doesnt work

### ISSUE THREAD

**Issue by MikeMueller101** [Xilinx/linux-xlnx#58]
Hello,

I try to run config my linux kernel to only use core0:
therefore i added the following into the bootargs: maxcpus=1
i started linux, but it still uses core1...
Here the kernel log: http://paste.ubuntu.com/11734402

the goal is to run linux on core0 and bare metal on core1.

here is how i created my boot.bin:
```
echo "img:{[bootloader] tmp/red_pitaya_0_92.fsbl/executable.elf tmp/red_pitaya_0_92.bit tmp/u-boot.elf app_cpu1.elf}" > tmp/boot.bif
bootgen -image tmp/boot.bif -w -o i boot.bin
```

XAPP1078 mentiones that i need to modify the cpu1_bootvec.bin
http://www.wiki.xilinx.com/XAPP1078+Latest+Information

On the other hand XAPP1079 mentions the following: 
"FSBL now supports multiple ELF files so the customized FSBL has been removed from the repository and the dummy cpu1_bootvec.bin file is no longer required so it has been removed from the bootgen.bif file."
http://www.wiki.xilinx.com/XAPP1079+Latest+Information

Develop Env: Vivado SDK 2015.1
My Platform:
HW: Xilinx Zynq 7010 Soc
Linux Kernel: https://github.com/Xilinx/linux-xlnx/archive/xilinx-v2015.1.tar.gz

Can someone explain whats the way to make it work?

**Comment by michalsimek** [comment]
Only 1 cpu is used by Linux.
Jan  1 01:00:06 red-pitaya kernel: Brought up 1 CPUs
Jan  1 01:00:06 red-pitaya kernel: SMP: Total of 1 processors activated.

why do you think that Linux is using core1?

**Comment by MikeMueller101** [comment]
cat /proc/cpuinfo shows two cores!

**Comment by michalsimek** [comment]
c&p log please. Also please use the latest version and retest. 
On 4.0 with maxcpu=1 I am getting this
zynq> cat /proc/cpuinfo 
processor	: 0
model name	: ARMv7 Processor rev 0 (v7l)
BogoMIPS	: 1332.01
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpd32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x3
CPU part	: 0xc09
CPU revision	: 0

Hardware	: Xilinx Zynq Platform
Revision	: 0000
Serial		: 0000000000000000

with zynq_zc702.dts

**Comment by MikeMueller101** [comment]
Ok will test. Do you have an archive of the latest kernel and is it stable?

**Comment by michalsimek** [comment]
master branch in the repo.

**Comment by MikeMueller101** [comment]
Ok. Was there recently a bug fixed, that would explain why i see this issue!?

**Comment by MikeMueller101** [comment]
here the info:

kernel info:
```
root@red-pitaya:~# uname -a
Linux red-pitaya 3.18.0-xilinx #1 SMP PREEMPT Fri Jun 19 11:43:34 EDT 2015 armv7l armv7l armv7l GNU/Linux
```

cpuinfo:
```
root@red-pitaya:~# cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 0 (v7l)
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpd32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0

processor       : 1
model name      : ARMv7 Processor rev 0 (v7l)
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpd32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc09
CPU revision    : 0

Hardware        : Xilinx Zynq Platform
Revision        : 0003
Serial          : 0000000000000000
```

**Comment by MikeMueller101** [comment]
@michalsimek i updated the kernel, but still see the same issue. any idea?
```
$ uname -a
Linux red-pitaya 4.0.0-xilinx-17488-gc70fa9e-dirty #1 SMP PREEMPT Sat Jun 20 06:14:57 EDT 2015 armv7l armv7l armv7l GNU/Linux
```

**Comment by michalsimek** [comment]
Based on maxcpus description you can see that it is restriction to boot time cpus. I was playing with it and user space can enable second CPU via hotplug. It means you should disable HOTPLUG in kernel .config file and retest. Also please check your rootfs setup what you do there. 
Another option is to disable SMP.

**Comment by MikeMueller101** [comment]
"Also please check your rootfs setup what you do there." ... do you somth like echo 0 > /sys/devices/system/cpu/cpu6/online in bashrc? ...i dont enable/disable the second cpu.

**Comment by michalsimek** [comment]
Jan  1 01:00:07 red-pitaya kernel: Freeing unused kernel memory: 224K (c072a000 - c0762000)
Jan  1 01:00:07 red-pitaya kernel: random: init urandom read with 8 bits of entropy available
Jan  1 01:00:07 red-pitaya kernel: CPU1: thread -1, cpu 1, socket 0, mpidr 80000001

**Comment by michalsimek** [comment]
this is done coming from user space. Disable HOTPLUG. Kernel just doing what you are asking for. Disable HOTPLUG or SMP and your problem should be solved.

**Comment by MikeMueller101** [comment]
did you disable HOTPLUG or SMP to get maxcpus work?

i want to understand if its a bug or not!

**Comment by MikeMueller101** [comment]
@michalsimek do you have any update regarding this issue?

**Comment by michalsimek** [comment]
As I told you before - I can't see any problem with the kernel. It is probably user space which is doing something what you don't want. Dosable hotplug and SMP and you should be fine.
