### ISSUE TITLE
master and zync-soc hangs when using GPIO

### ISSUE THREAD

**Issue by finomen** [Xilinx/linux-xlnx#59]
I tried both master and zync-soc branches.
In devicetree I have four gpios like this
axi_gpio_1: gpio@41240000 {
			#gpio-cells = <2>;
			compatible = "xlnx,xps-gpio-1.00.a";
			gpio-controller ;
			interrupt-parent = <&intc>;
			interrupts = <0 31 4>;
			reg = <0x41240000 0x10000>;
			xlnx,all-inputs = <0x0>;
			xlnx,all-inputs-2 = <0x0>;
			xlnx,all-outputs = <0x1>;
			xlnx,all-outputs-2 = <0x0>;
			xlnx,dout-default = <0x41240000>;
			xlnx,dout-default-2 = <0x00000000>;
			xlnx,gpio-width = <0x1>;
			xlnx,gpio2-width = <0x20>;
			xlnx,interrupt-present = <0x1>;
			xlnx,is-dual = <0x0>;
			xlnx,tri-default = <0x4124FFFF>;
			xlnx,tri-default-2 = <0xFFFFFFFF>;
		};
In vivado they connected to FPGA (interconnect). When I reading GPIO value or changing direction through sysfs or from my kernel module system hangs.

With old (3.0.9) kernel and xps project all works fine. If I execute simple code, that executes Xil_In32/Xil_Out32 GPIO's works fine. 

In old devicetree GPIOs looks like
axi_gpio_0: gpio@41240000 {
			#gpio-cells = <0x2>;
			compatible = "xlnx,axi-gpio-1.01.b", "xlnx,xps-gpio-1.00.a";
			gpio-controller;
			reg = <0x41240000 0x10000>;
			xlnx,all-inputs = <0x0>;
			xlnx,all-inputs-2 = <0x0>;
			xlnx,dout-default = <0x0>;
			xlnx,dout-default-2 = <0x0>;
			xlnx,gpio-width = <0x1>;
			xlnx,gpio2-width = <0x20>;
			xlnx,instance = "axi_gpio_0";
			xlnx,interrupt-present = <0x1>;
			xlnx,is-dual = <0x0>;
			xlnx,tri-default = <0xffffffff>;
			xlnx,tri-default-2 = <0xffffffff>;
		};

Although old kernel use numbers 252-254 for GPIO, but 4..0/4.1 kernel use 1020-1023.

**Comment by michalsimek** [comment]
There is new code in mailine for xilinx gpio without irq support. In xilinx tree we do use older code with irq support. Kernel version, information about your testcase are needed. Also please use xilinx forums.

**Comment by learningendless** [comment]
@michalsimek ,Do you means that the master branch code does not support gpio IRQ? Now I want to use GPIO54 as a input gpio with interrupt enabled! Is this supported? Looking forward for your response. Thanks!
