### ISSUE TITLE
udev missing the driver file when apllication is shutdown

### ISSUE THREAD

**Issue by VarunRajendran** [Xilinx/linux-xlnx#60]
Hi, I am using "Linux zynq 3.10.0-xilinx" #3 SMP PREEMPT for my project
I did checkout of the tag Xilinx v14.7
I have cross compiled the kernel drivers.

I am using Zynq Z702 board, I have used the booting file for petalinux on Zynq from the below mentioned site. 
http://www.wiki.xilinx.com/Zynq+14.7-2013.3+Release

I have used insmod to add my kernel driver in the /dev. After that I start my application.
I am succesfully able to run my project.

The problem I am facing:
1) When the application is shutdown, driver file is missing from the /dev
2) When I restart the application, the application is not initizaling.

I would like to know whether the driver file will be missing, after application exits?
and I request anyone to provide solution for this issue.

**Comment by michalsimek** [comment]
please use the latest&greatest kernel and retest.

**Comment by VarunRajendran** [comment]
Thanks for the information. I will test with the latest kernal driver file.

**Comment by VarunRajendran** [comment]
As per your suggestion, I have checked with the latest kernel (Linux zynq 4.0.0-xilinx) and the issue still prevails. When the application is shutdown, driver file is missing from the /dev.
Please provide me the solution for this issue.

**Comment by michalsimek** [comment]
You are writing that you use your own module not any one which is provided by us. It is impossible to help you when you are not providing any code and likely there is any problem with your code. Anyway this is not the right way how to get attention to your problem. Please use Xilinx forums where support team can help you with your problem.
