### ISSUE TITLE
xilinx_emacps.c on Zynq does not work with 2 ethernet interfaces

### ISSUE THREAD

**Issue by uwojak** [Xilinx/linux-xlnx#7]
Using the xilinx_emacps on Zynq fails when using 2 eth interfaces.

The following patch fixes this. The original code uses the same id for both mii busses which fails.

diff --git a/drivers/net/ethernet/xilinx/xilinx_emacps.c b/drivers/net/ethernet/xilinx/xilinx_emacps.c
index 9a5c863..d05c72b 100644
--- a/drivers/net/ethernet/xilinx/xilinx_emacps.c
+++ b/drivers/net/ethernet/xilinx/xilinx_emacps.c
@@ -878,7 +878,7 @@ static int xemacps_mii_init(struct net_local *lp)
 	for (i = 0; i < PHY_MAX_ADDR; i++)
 		lp->mii_bus->irq[i] = PHY_POLL;
 	npp = of_get_parent(np);
-	of_address_to_resource(npp, 0, &res);
+	of_address_to_resource(np, 0, &res);
 	snprintf(lp->mii_bus->id, MII_BUS_ID_SIZE, "%.8llx",
 		 (unsigned long long)res.start);
 	if (of_mdiobus_register(lp->mii_bus, np))

**Comment by michalsimek** [comment]
Fixed long time ago.
