### ISSUE TITLE
How to do atomic operation while using OCM to communicate two core??

### ISSUE THREAD

**Issue by moypray** [Xilinx/linux-xlnx#74]
Hi,  I am using zynq 7000 chip and I use CPU0 to run Linux, cpu1 to run bare Executable file.
And I need the two core communication using OCM,  now it is working.

but i do not know how to keep the resource access by one cpu at a same time(just the atomic operation) ?

Does anyone help me here????

thanks!!

**Comment by moypray** [comment]
I am trying to use DDR memory as LOCK to sync up the two CPU, but the memory has other problems.

**Comment by michalsimek** [comment]
Hi,

you can create sync routines in sw or use hw resources like mailbox IP for doing that. 
Anyway please move your request to Xilinx forum.

Thanks,
Michal
